src/Entity/Properties.php
<?php

namespace App\Entity;

use App\Repository\PropertiesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PropertiesRepository::class)
 */
class Properties
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $adresse_numero;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse_libelle;

    /**
     * @ORM\Column(type="integer")
     */
    private $adresse_cp;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse_ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse_pays;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_piece;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_parking;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_principale;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $owner_firstname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $owner_lastname;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $owner_phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $owner_email;

    /**
     * @ORM\OneToMany(targetEntity=Pictures::class, mappedBy="relatedProperty", orphanRemoval=true)
     */
    private $pictures;

    public function __construct()
    {
        $this->pictures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAdresseNumero(): ?int
    {
        return $this->adresse_numero;
    }

    public function setAdresseNumero(?int $adresse_numero): self
    {
        $this->adresse_numero = $adresse_numero;

        return $this;
    }

    public function getAdresseLibelle(): ?string
    {
        return $this->adresse_libelle;
    }

    public function setAdresseLibelle(string $adresse_libelle): self
    {
        $this->adresse_libelle = $adresse_libelle;

        return $this;
    }

    public function getAdresseCp(): ?int
    {
        return $this->adresse_cp;
    }

    public function setAdresseCp(int $adresse_cp): self
    {
        $this->adresse_cp = $adresse_cp;

        return $this;
    }

    public function getAdresseVille(): ?string
    {
        return $this->adresse_ville;
    }

    public function setAdresseVille(string $adresse_ville): self
    {
        $this->adresse_ville = $adresse_ville;

        return $this;
    }

    public function getAdressePays(): ?string
    {
        return $this->adresse_pays;
    }

    public function setAdressePays(string $adresse_pays): self
    {
        $this->adresse_pays = $adresse_pays;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getNombrePiece(): ?int
    {
        return $this->nombre_piece;
    }

    public function setNombrePiece(int $nombre_piece): self
    {
        $this->nombre_piece = $nombre_piece;

        return $this;
    }

    public function getNombreParking(): ?int
    {
        return $this->nombre_parking;
    }

    public function setNombreParking(int $nombre_parking): self
    {
        $this->nombre_parking = $nombre_parking;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImagePrincipale(): ?string
    {
        return $this->image_principale;
    }

    public function setImagePrincipale(?string $image_principale): self
    {
        $this->image_principale = $image_principale;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getOwnerFirstname(): ?string
    {
        return $this->owner_firstname;
    }

    public function setOwnerFirstname(?string $owner_firstname): self
    {
        $this->owner_firstname = $owner_firstname;

        return $this;
    }

    public function getOwnerLastname(): ?string
    {
        return $this->owner_lastname;
    }

    public function setOwnerLastname(?string $owner_lastname): self
    {
        $this->owner_lastname = $owner_lastname;

        return $this;
    }

    public function getOwnerPhone(): ?string
    {
        return $this->owner_phone;
    }

    public function setOwnerPhone(?string $owner_phone): self
    {
        $this->owner_phone = $owner_phone;

        return $this;
    }

    public function getOwnerEmail(): ?string
    {
        return $this->owner_email;
    }

    public function setOwnerEmail(?string $owner_email): self
    {
        $this->owner_email = $owner_email;

        return $this;
    }

    /**
     * @return Collection|Pictures[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Pictures $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setRelatedProperty($this);
        }

        return $this;
    }

    public function removePicture(Pictures $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getRelatedProperty() === $this) {
                $picture->setRelatedProperty(null);
            }
        }

        return $this;
    }

    /**
     * Generates the magic method
     *
     */
    public function __toString(){
        // to show the name of the Category in the select
        return (string) $this->id;
        // to show the id of the Category in the select
        // return $this->id;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Properties;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('adresse_numero')
            ->add('adresse_libelle')
            ->add('adresse_cp')
            ->add('adresse_ville')
            ->add('adresse_pays')
            ->add('prix')
            ->add('surface')
            ->add('nombre_piece')
            ->add('nombre_parking')
            ->add('description')
            ->add('image_principale')
            ->add('owner_firstname')
            ->add('owner_lastname')
            ->add('owner_phone')
            ->add('owner_email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Properties::class,
        ]);
    }
}

src/Controller/PropertiesController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use App\Entity\Properties;
use App\Entity\Pictures;
use App\Form\PropertyType;
use App\Form\PicturesType;
use Doctrine\Persistence\ObjectManager;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;

class PropertiesController extends AbstractController
{
    /**
     * @Route("/properties", name="properties")
     */
    public function index(): Response
    {
      $repo = $this->getDoctrine()->getRepository(Properties::class);

      $properties = $repo->findAll();

        return $this->render('properties/index.html.twig', [
            'controller_name' => 'PropertiesController',
            'properties' => $properties
        ]);
    }

    /**
     * @Route("/", name="home")
     */
    public function home() {

      $repo = $this->getDoctrine()->getRepository(Properties::class);

      $properties = $repo->findAll();

        return $this->render('properties/home.html.twig', [
          'properties' => $properties
        ]);
    }

    /**
    *@Route("/properties/new", name="properties_create")
    *@Route("/properties/{id}/edit", name="properties_edit")
    */
    public function formProperty(Properties $property = null, Request $request, EntityManagerInterface $manager){

      if(!$property) {
        $property = new Properties();
      }

      $form = $this->createForm(PropertyType::class, $property);

      $form->handleRequest($request);

      if ($form->isSubmitted() && $form->isValid()) {
        if(!$property->getId()) {
          $property->setCreatedAt(new \DateTime());
        }

        $manager->persist($property);
        $manager->flush();

        return $this->redirectToRoute('property_show', ['id' => $property->getId()]);
      }

      return $this->render('properties/create.html.twig', [
        'formProperty' => $form->createView(),
        'editMode' => $property->getId() != null
      ]);
    }

    /**
    *@Route("/properties/{id}/picturesAdd", name="properties_picturesAdd")
    */
    public function picturesAdd(Properties $property, Request $request, EntityManagerInterface $manager) {

      $pictures = new Pictures();
      $form = $this->createForm(PicturesType::class, $pictures);

      $form->handleRequest($request);

      if ($form->isSubmitted() && $form->isValid()) {
        $pictures->setRelatedProperty($property);
        $manager->persist($pictures);
        $manager->flush();
        $property->addPicture($pictures);
        $manager->persist($property);
        $manager->flush();

        return $this->redirectToRoute('property_show', ['id' => $property->getId()]);
      }

      return $this->render('properties/picturesadd.html.twig', [
        'formPictures' => $form->createView()
      ]);
    }

    /**
    *@Route("/properties/{id}/delete", name="properties_delete")
    */
    public function delete(Properties $property, EntityManagerInterface $manager) {
      $manager->remove($property);
      $manager->flush();

      return $this->redirectToRoute('home');
    }

    /**
    *@Route("/property/{id_prop}/picture/{id_pic}/delete", name="picture_delete")
    */
    public function deletePicture($id_prop, $id_pic, EntityManagerInterface $manager) {

      $repo = $this->getDoctrine()->getRepository(Properties::class);
      $picrepo = $this->getDoctrine()->getRepository(Pictures::class);

      $property = $repo->findOneBy(array('id' => $id_prop));
      $picture = $picrepo->findOneBy(array('id' => $id_pic));

      $property->removePicture($picture);
      $manager->persist($property);
      $manager->flush();
      return $this->redirectToRoute('property_show', ['id' => $property->getId()]);
    }

    /**
    * @Route("/properties/{id}", name="property_show")
    */
    public function show($id) {
      $repo = $this->getDoctrine()->getRepository(Properties::class);

      $property = $repo->find($id);

      return $this->render('properties/show.html.twig', [
        'property' => $property
      ]);
    }
}

templates/properties/create.html.twig
{% extends 'base.html.twig' %}

{% form_theme formProperty 'bootstrap_4_layout.html.twig' %}

{% block body %}

<h1>Création</h1>

{{ form_start(formProperty) }}

{{ form_widget(formProperty) }}

<button type="submit" class="btn btn-success">
  {% if editMode %}
    Enregister les modifs
  {% else %}
    Ajouter la propriétée
    {% endif %}
</button>

{{ form_end(formProperty) }}

{% endblock %}

templates/properties/home.html.twig
{% extends 'base.html.twig'%}

{% block body %}

  <h1>Tableau de bord</h1>

  <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Titre</th>
      <th scope="col">Adresse</th>
      <th scope="col">Prix</th>
      <th scope="col">Surface</th>
      <th scope="col">N° Pièces</th>
      <th scope="col">N° Parking</th>
      <th scope="col">Date de création</th>
      <th scope="col">N° Propriétaire</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for property in properties %}
    <tr class="
    {% if property.id % 2 == 0 %}
      table-success
    {% else %}
      table-info
    {% endif %}
    ">
      <th scope="row">{{property.title}}</th>
      <td>{{property.adresseLibelle}}<br>{{property.adresseCp}} {{property.adresseVille}}</td>
      <td>{{property.prix}}</td>
      <td>{{property.surface}}</td>
      <td>{{property.nombrePiece}}</td>
      <td>{{property.nombreParking}}</td>
      <td>{{ property.createdAt | date('d/m/Y') }}</td>
      <td>{{property.ownerPhone}}</td>
      <td> <a href="{{ path('properties_edit', {'id': property.id}) }}" class="btn btn-warning">0</a></td>
      <td> <a href="{{ path('properties_delete', {'id': property.id}) }}" onclick="return confirm('are u sure?')" class="btn btn-danger">X</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/properties/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PropertiesController!{% endblock %}

{% block body %}

<section class="properties row">

  {% for property in properties %}
  <div class="property col-4">
    <h2>{{ property.title }}</h2>
    <img src="{{ property.imagePrincipale }}" alt="">
    <div class="property_content">
      <p>{{ property.adresseNumero}} </br>
      {{ property.adresseLibelle}} </br>
      {{property.adresseCp}} {{property.adresseVille}}</p>
      <p>{{ property.prix }}</p>
      <p>{{ property.surface }}</p>
      <p>{{ property.nombrePiece }}</p>
      <p>{{ property.nombreParking }}</p>
      <p>Created ad {{ property.createdAt | date('d/m/Y') }} à {{ property.createdAt | date('H:i')}}</p>
      <a href="{{ path('property_show', {'id': property.id}) }}" class="btn btn-primary">Plus d'infos</a>
    </div>
  </div>
{% endfor %}

</section>

{% endblock %}

templates/properties/picturesadd.html.twig
{% extends 'base.html.twig' %}

{% form_theme formPictures 'bootstrap_4_layout.html.twig' %}

{% block body %}

<h1>Ajouter une image</h1>

{{ form_start(formPictures) }}

{{ form_widget(formPictures) }}

<button type="submit" class="btn btn-success">
  Ajouter
</button>

{{ form_end(formPictures) }}

{% endblock %}

templates/properties/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="show_property">
  <h1>{{ property.title }}</h2>
  <img src="{{ property.imagePrincipale }}" alt="">
  <div class="property_content">
    <h2>Adresse</h2>
    <p>{{ property.adresseNumero}}
    {{ property.adresseLibelle}} </br>
    {{property.adresseCp}} {{property.adresseVille}}</p>
    <h2>Propriétaire</h2>
    <p>
      Nom : {{ property.ownerLastname }}
      <br> Prenom : {{ property.ownerFirstname}}
      <br> Phone : {{ property.ownerPhone }}
      <br> Email : {{ property.ownerEmail }}
    </p>
    <h2>Détails</h2>
    <p>Prix : {{ property.prix }}</p>
    <p>Surface : {{ property.surface }}</p>
    <p>N° Pièces : {{ property.nombrePiece }}</p>
    <p>N° Places de parking : {{ property.nombreParking }}</p>
    <p>Offre enregistrée le : {{ property.createdAt | date('d/m/Y') }} à {{ property.createdAt | date('H:i')}}</p>
    <h2> Description </h2>
    <p>{{ property.description }}</p>
    <h2>Images</h2>
    <div class="container">
      <div class="row">
        {% for item in property.pictures %}
          <div class="container col-4">
            <img src="{{ item.url }}" class="img-fluid" alt="...">
            <div class="title row">
                <h5 class="text- col-6"> {{  item.name }}</h5>
                <a href="{{ path('picture_delete', {'id_prop' : property.id, "id_pic" : item.id})}}" class="btn btn-success col-4">X</a>
            </div>
          </div>
        {% endfor %}

      </div>
    </div>
    <a href="{{ path('properties_edit', {'id': property.id}) }}" class="btn btn-primary">Modifier</a>
    <a href="{{ path('properties_picturesAdd', {'id': property.id}) }}" class="btn btn-success">Ajouter des images</a>
    <a href="{{ path('properties_delete', {'id': property.id}) }}" onclick="return confirm('are u sure?')" class="btn btn-secondary">Supprimer</a>
  </div>
</div>
{% endblock %}